apiVersion: v1
kind: Service
metadata:
    labels:
        app: react-intro
    name: react-intro-svc
spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
    selector:
        app: react-intro
    type: ClusterIP